### ISSUE TITLE
Dissolve with stat cause a crash with QGIS 2.16.3

### ISSUE THREAD

**Issue by FERRATON** [UMR-PASSAGES/DissolveWithStats#8]
with any file execution the plugin cause a mnidump under QGIS 2.16.3
Work properly with QGIS 2.16.1

**Comment by juliepierson** [comment]
Hi, works ok for me in QGIS 2.18.1. Ok for you too ?

**Comment by FERRATON** [comment]
It's OK
cf : https://hub.qgis.org/issues/15707

**Comment by juliepierson** [comment]
Great, thanks.
